// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.Pawpi.Infrastructure.Data;

#nullable disable

namespace Pri.Pawpi.Infrastructure.Migrations
{
    [DbContext(typeof(PawpiDbContext))]
    [Migration("20231112125452_AddCustomerUsers")]
    partial class AddCustomerUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedicationPet", b =>
                {
                    b.Property<int>("MedicationsId")
                        .HasColumnType("int");

                    b.Property<int>("PetsId")
                        .HasColumnType("int");

                    b.HasKey("MedicationsId", "PetsId");

                    b.HasIndex("PetsId");

                    b.ToTable("MedicationPet");

                    b.HasData(
                        new
                        {
                            MedicationsId = 1,
                            PetsId = 1
                        },
                        new
                        {
                            MedicationsId = 2,
                            PetsId = 1
                        },
                        new
                        {
                            MedicationsId = 3,
                            PetsId = 2
                        },
                        new
                        {
                            MedicationsId = 4,
                            PetsId = 2
                        },
                        new
                        {
                            MedicationsId = 5,
                            PetsId = 3
                        },
                        new
                        {
                            MedicationsId = 6,
                            PetsId = 3
                        },
                        new
                        {
                            MedicationsId = 7,
                            PetsId = 4
                        },
                        new
                        {
                            MedicationsId = 8,
                            PetsId = 4
                        },
                        new
                        {
                            MedicationsId = 9,
                            PetsId = 5
                        },
                        new
                        {
                            MedicationsId = 10,
                            PetsId = 5
                        },
                        new
                        {
                            MedicationsId = 11,
                            PetsId = 6
                        },
                        new
                        {
                            MedicationsId = 12,
                            PetsId = 6
                        },
                        new
                        {
                            MedicationsId = 13,
                            PetsId = 7
                        },
                        new
                        {
                            MedicationsId = 14,
                            PetsId = 7
                        },
                        new
                        {
                            MedicationsId = 15,
                            PetsId = 8
                        },
                        new
                        {
                            MedicationsId = 13,
                            PetsId = 8
                        },
                        new
                        {
                            MedicationsId = 14,
                            PetsId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "7329779e-593b-46e0-8171-8e59b4a41b4c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "96d7e490-bc95-4d83-b766-18ecbe03b349",
                            Name = "Veterinarian",
                            NormalizedName = "VETERINARIAN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "984515c6-837e-4db2-88eb-2352371f2e41",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PracticeVeterinarian", b =>
                {
                    b.Property<int>("PracticesId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariansId")
                        .HasColumnType("int");

                    b.HasKey("PracticesId", "VeterinariansId");

                    b.HasIndex("VeterinariansId");

                    b.ToTable("PracticeVeterinarian");

                    b.HasData(
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 1
                        },
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 2
                        },
                        new
                        {
                            PracticesId = 2,
                            VeterinariansId = 3
                        },
                        new
                        {
                            PracticesId = 2,
                            VeterinariansId = 4
                        },
                        new
                        {
                            PracticesId = 3,
                            VeterinariansId = 5
                        },
                        new
                        {
                            PracticesId = 3,
                            VeterinariansId = 1
                        },
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 3
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("VeterinarianId")
                        .IsUnique()
                        .HasFilter("[VeterinarianId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d916bb95-d881-4f9f-9a8a-90722e3a1eba",
                            CustomerId = 1,
                            Email = "svends@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SVENDS@GMAIL.COM",
                            NormalizedUserName = "SVENDS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAK1q9TNqJ3A3aWPP5DXzm76saGCpxyeOR1aus7fdplqecXy2OsSj/CaTp9otygxJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61463487-5a27-4eb4-b928-9601448d1a4d",
                            TwoFactorEnabled = false,
                            UserName = "svends@gmail.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c262cc53-8161-485e-84e4-fe043fbade80",
                            CustomerId = 2,
                            Email = "vb@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VB@GMAIL.COM",
                            NormalizedUserName = "VB@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFL2wpVDyjqcsc3TwSRF0eb24qRM7IawYOgie0S5Dw09NADny5bdypXlCDIuiqhioA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac2fe3a3-721d-4bbf-a08f-13d47640286c",
                            TwoFactorEnabled = false,
                            UserName = "vb@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e8c569d-0658-4636-9e80-6e433a4200ab",
                            CustomerId = 3,
                            Email = "kdv@outlook.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KDV@OUTLOOK.COM",
                            NormalizedUserName = "KDV@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPbuizkREL+7jOooWQBYBsBaCWxtM7kDsGwzveyCslvzlY3orz/0R/dQ6DZdrkHcZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f34aee25-e77d-4a2a-b7ca-d8f78f54ca9f",
                            TwoFactorEnabled = false,
                            UserName = "kdv@outlook.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "874d4cc6-e4ef-4936-8a03-48e525eaf05b",
                            CustomerId = 4,
                            Email = "makkermaat@telenet.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAKKERMAAT@TELENET.BE",
                            NormalizedUserName = "MAKKERMAAT@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAECfDeXErwu+O9RW5RIliZdzrqTtt12g1qTcgomHxRiObrppM1kJipzNm9JiuN++Evg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d57db20a-f45b-406c-b9ba-a2a3f8d892b4",
                            TwoFactorEnabled = false,
                            UserName = "makkermaat@telenet.be"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bc0e8da6-b978-4134-a807-68d04c96a5a3",
                            CustomerId = 5,
                            Email = "sarahdv@proximus.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAHDV@PROXIMUS.BE",
                            NormalizedUserName = "SARAHDV@PROXIMUS.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEOjAwwDlNYBTkus0opJcC0dHKzEf5PQYdzOJQH96MpvRojDizU5XMjvtfMaJAqiNLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b52db6b-4f3c-4aa3-afa6-94f702f87b28",
                            TwoFactorEnabled = false,
                            UserName = "sarahdv@proximus.be"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "200128a6-b82b-4230-9dc2-fb0c59890d5e",
                            CustomerId = 6,
                            Email = "jdv@yahoo.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JDV@YAHOO.COM",
                            NormalizedUserName = "JDV@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEA8swpX3/LsgkJvh6EBtWNT2o3y9RrkEO7pUXN/UDrkEh4grPXK9l/6Xdb7iGpU10w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e15f983c-a9c1-485c-a5ea-3ea58d435d66",
                            TwoFactorEnabled = false,
                            UserName = "jdv@yahoo.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78eeb986-eadd-4249-830c-631aec567e56",
                            CustomerId = 7,
                            Email = "mieketjeeeeh@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIEKETJEEEEH@GMAIL.COM",
                            NormalizedUserName = "MIEKETJEEEEH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGUYk05UcsWaBixTC+Yi6ouCmhzOIzpBoNriScE5Hny3lke1kdfbQF72oHbratJWmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62b06efb-ce7b-4676-905b-8945fa1e53f1",
                            TwoFactorEnabled = false,
                            UserName = "mieketjeeeeh@gmail.com"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "645aae43-830c-4720-84e3-0c719a31c807",
                            CustomerId = 8,
                            Email = "jeffkeeuh@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JEFFKEEUH@GMAIL.COM",
                            NormalizedUserName = "JEFFKEEUH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKvJVayCkTxr4WNz+kgsoJOT/y6/hc4UN1ePyIsC8px650bh6oPzEEyq708puoL6ZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3afa520a-de61-4f32-bbba-a7e809ce3ca5",
                            TwoFactorEnabled = false,
                            UserName = "jeffkeeuh@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "490ceaec-2eb1-4637-8ede-9a5eedd59315",
                            CustomerId = 9,
                            Email = "hansdissen@telenet.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HANSDISSEN@TELENET.BE",
                            NormalizedUserName = "HANSDISSEN@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEPUmsYCdjxFhKo0u14rANoxBGei0Y+qUscnf24F92uhzmu1SZQpSCOhPA8E+dmFdhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76dbc078-1d8e-48b4-a20c-a2a5f048406e",
                            TwoFactorEnabled = false,
                            UserName = "hansdissen@telenet.be"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "494bf347-1d94-410e-9148-5373159f1b80",
                            CustomerId = 10,
                            Email = "chaydz@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHAYDZ@GMAIL.COM",
                            NormalizedUserName = "CHAYDZ@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEK+wL/bG3aUUz9kip2kN3UI7R0ANKyCrZ5f26JioVWhpieESX+JzMy7lDg3KlS0ifw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "498c0772-4b0d-4183-9707-706e934f3be5",
                            TwoFactorEnabled = false,
                            UserName = "chaydz@gmail.com"
                        },
                        new
                        {
                            Id = "12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb6e678b-59f8-4619-bc85-9ab2c15e810b",
                            CustomerId = 999,
                            Email = "Customer@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@TEST.COM",
                            NormalizedUserName = "CUSTOMER@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEL46eNB+ab+lXhH4zg7s97JRFber63jO6XTyBYwysOE/IoZ8GeH6fm0Y6MpFvF0AAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d90f307-8270-47a6-a461-1d74a81a9ee1",
                            TwoFactorEnabled = false,
                            UserName = "Customer@test.com"
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfConsultation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocumentFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfConsultation = new DateTime(2023, 11, 12, 13, 54, 52, 330, DateTimeKind.Local).AddTicks(2094),
                            Diagnosis = "Controle",
                            Notes = "Staat wat mager",
                            PetId = 1,
                            Title = "First Consultation",
                            Treatment = "None",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfConsultation = new DateTime(2023, 11, 12, 13, 54, 52, 330, DateTimeKind.Local).AddTicks(2178),
                            Diagnosis = "Hond in kwestie heeft gras gegeten en moet overgeven",
                            Notes = "",
                            PetId = 1,
                            Title = "Overgeven",
                            Treatment = "Gaat over",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfConsultation = new DateTime(2023, 11, 12, 13, 54, 52, 330, DateTimeKind.Local).AddTicks(2180),
                            Diagnosis = "Vaccinatie",
                            Notes = "",
                            PetId = 2,
                            Title = "Vaccinatie",
                            Treatment = "",
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfConsultation = new DateTime(2023, 11, 12, 13, 54, 52, 330, DateTimeKind.Local).AddTicks(2183),
                            Diagnosis = "Tanden zijn slecht onderhouden",
                            Notes = "",
                            PetId = 3,
                            Title = "Tanden",
                            Treatment = "Medicatie en poeten",
                            VeterinarianId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateOfConsultation = new DateTime(2023, 11, 12, 13, 54, 52, 330, DateTimeKind.Local).AddTicks(2185),
                            Diagnosis = "Vaccinatie",
                            Notes = "",
                            PetId = 2,
                            Title = "Vaccinatie",
                            Treatment = "",
                            VeterinarianId = 3
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            Birth = new DateTime(1991, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "svends@gmail.com",
                            FirstName = "Sven",
                            LastName = "De Schagt",
                            Phone = "0478 12 34 56",
                            Postal = "8000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Langestraat 56",
                            Birth = new DateTime(1981, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "vb@gmail.com",
                            FirstName = "Jan",
                            LastName = "Vanbergen",
                            Phone = "0478 12 69 99",
                            Postal = "9000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 134",
                            Birth = new DateTime(1971, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Oedelem",
                            Email = "kdv@outlook.com",
                            FirstName = "Karel",
                            LastName = "De Vos",
                            Phone = "0488 11 43 39",
                            Postal = "8730",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lippenslaan 45",
                            Birth = new DateTime(1966, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "makkermaat@telenet.be",
                            FirstName = "Makker",
                            LastName = "Maat",
                            Phone = "0032459698738",
                            Postal = "8310",
                            PracticeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "lachenstraat 21",
                            Birth = new DateTime(2010, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "sarahdv@proximus.be",
                            FirstName = "Sarah",
                            LastName = "De Vriendt",
                            Phone = "0032459698738",
                            Postal = "8000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "zieligestraat 101",
                            Birth = new DateTime(1970, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "jdv@yahoo.com",
                            FirstName = "Johan",
                            LastName = "De Vriendt",
                            Phone = "2345563223",
                            Postal = "8310",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "stommestrat 102",
                            Birth = new DateTime(1940, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "mieketjeeeeh@gmail.com",
                            FirstName = "Mieke",
                            LastName = "Vanoverpoel",
                            Phone = "0032567844",
                            Postal = "9000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "stommestrat 102",
                            Birth = new DateTime(1950, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "jeffkeeuh@gmail.com",
                            FirstName = "Jef",
                            LastName = "Vanoverpoel",
                            Phone = "2234565463",
                            Postal = "9000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "lachenstraat 21",
                            Birth = new DateTime(2010, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "hansdissen@telenet.be",
                            FirstName = "Hans",
                            LastName = "Dissen",
                            Phone = "0032459698738",
                            Postal = "8000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "Hulstlo 21",
                            Birth = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Beernem",
                            Email = "chaydz@gmail.com",
                            FirstName = "Chayenne",
                            LastName = "De Zutter",
                            Phone = "0032459698738",
                            Postal = "8730",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 999,
                            Address = "Test",
                            Birth = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Test",
                            Email = "Customer@test.com",
                            FirstName = "Test",
                            LastName = "Test",
                            Phone = "0032459698738",
                            Postal = "9999",
                            PracticeId = 1
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SideEffects")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dosage = "2",
                            Frequency = "Once a day",
                            Name = "Rimadyl",
                            Notes = "Rimadyl is a non-steroidal anti-inflammatory drug (NSAID) of the propionic acid class that is used in humans and animals for the relief of pain and inflammation associated with osteoarthritis and for the control of postoperative pain associated with soft tissue and orthopedic surgeries in dogs."
                        },
                        new
                        {
                            Id = 2,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Tramadol",
                            Notes = "Tramadol, sold under the brand name Ultram among others, is an opioid pain medication used to treat moderate to moderately severe pain. When taken by mouth in an immediate-release formulation, the onset of pain relief usually begins within an hour."
                        },
                        new
                        {
                            Id = 3,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Gabapentin",
                            Notes = "Gabapentin, sold under the brand name Neurontin among others, is an anticonvulsant medication used to treat partial seizures, neuropathic pain, hot flashes, and restless legs syndrome."
                        },
                        new
                        {
                            Id = 4,
                            Dosage = "1",
                            Frequency = "Three times a day",
                            Name = "Apoquel",
                            Notes = "Apoquel is a medication that is used to treat itching and inflammation in dogs caused by a variety of diagnoses. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls itching within 24 hours."
                        },
                        new
                        {
                            Id = 5,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Cerenia",
                            Notes = "Cerenia is a medication that is used to treat vomiting in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls vomiting within 24 hours."
                        },
                        new
                        {
                            Id = 6,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Clavamox",
                            Notes = "Clavamox is a medication that is used to treat bacterial infections in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls bacterial infections within 24 hours."
                        },
                        new
                        {
                            Id = 7,
                            Dosage = "1",
                            Frequency = "Tree times a day",
                            Name = "Doxycycline",
                            Notes = "Doxycycline is a medication that is used to treat bacterial infections in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls bacterial infections within 24 hours."
                        },
                        new
                        {
                            Id = 8,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Enalapril",
                            Notes = "Enalapril is a medication that is used to treat heart failure in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls heart failure within 24 hours."
                        },
                        new
                        {
                            Id = 9,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Famotidine",
                            Notes = "Famotidine is a medication that is used to treat stomach ulcers in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls stomach ulcers within 24 hours."
                        },
                        new
                        {
                            Id = 10,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Fluoxetine",
                            Notes = "Fluoxetine is a medication that is used to treat anxiety in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls anxiety within 24 hours."
                        },
                        new
                        {
                            Id = 11,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Metronidazole",
                            Notes = "Metronidazole is a medication that is used to treat diarrhea in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls diarrhea within 24 hours."
                        },
                        new
                        {
                            Id = 12,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Mirtazapine",
                            Notes = "Mirtazapine is a medication that is used to treat appetite loss in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls appetite loss within 24 hours."
                        },
                        new
                        {
                            Id = 13,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Prednisone",
                            Notes = "Prednisone is a medication that is used to treat inflammation in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls inflammation within 24 hours."
                        },
                        new
                        {
                            Id = 14,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Praziquantel",
                            Notes = "Praziquantel is a medication that is used to treat tapeworms in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls tapeworms within 24 hours."
                        },
                        new
                        {
                            Id = 15,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Simparica",
                            Notes = "Simparica is a medication that is used to treat fleas and ticks in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls fleas and ticks within 24 hours."
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CallName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PedigreeFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Dog",
                            Breed = "Golden Retriever",
                            CallName = "Bella",
                            Color = "Golden",
                            CustomerId = 1,
                            Name = "Dunehills Love at first sight",
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Dog",
                            Breed = "Australian Shepherd",
                            CallName = "Luna",
                            Color = "White/Brown",
                            CustomerId = 1,
                            Name = "New glory to the moon",
                            Weight = 20.0
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Dog",
                            Breed = "New Foundland",
                            CallName = "Sky",
                            Color = "Black",
                            CustomerId = 2,
                            Name = "West horizon blue sky",
                            Weight = 50.0
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Dog",
                            Breed = "Chihuahua",
                            CallName = "Ratty",
                            Color = "Brown",
                            CustomerId = 3,
                            Name = "Left angle handbag",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "Dog",
                            Breed = "German Shepherd",
                            CallName = "Doug",
                            Color = "Black",
                            CustomerId = 2,
                            Name = "Dark sky thunderstorm",
                            Weight = 40.0
                        },
                        new
                        {
                            Id = 6,
                            AnimalType = "Cat",
                            Breed = "Persian",
                            CallName = "Sunny",
                            Color = "White",
                            CustomerId = 4,
                            Name = "Seven lives to the sun",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 7,
                            AnimalType = "Cat",
                            Breed = "Ragdoll",
                            CallName = "Ellie",
                            Color = "Brown",
                            CustomerId = 5,
                            Name = "The last of us",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 8,
                            AnimalType = "Cat",
                            Breed = "Maine Coon",
                            CallName = "Mio",
                            Color = "White",
                            CustomerId = 5,
                            Name = "Chronicles of ouroboros",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 9,
                            AnimalType = "Fish",
                            Breed = "Goldfish",
                            CallName = "blub",
                            Color = "Gold",
                            CustomerId = 1,
                            Name = "Sharktale the blue",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 10,
                            AnimalType = "Fish",
                            Breed = "Droge vis",
                            CallName = "sink",
                            Color = "Blue",
                            CustomerId = 2,
                            Name = "Dark cold blue sea",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 11,
                            AnimalType = "Horse",
                            Breed = "Horse",
                            CallName = "Stallion",
                            Color = "Brown",
                            CustomerId = 3,
                            Name = "Big horse on the field",
                            Weight = 500.0
                        },
                        new
                        {
                            Id = 12,
                            AnimalType = "Snake",
                            Breed = "Viper",
                            CallName = "Noodle",
                            Color = "Green",
                            CustomerId = 6,
                            Name = "Slithering down the road",
                            Weight = 1.0
                        },
                        new
                        {
                            Id = 13,
                            AnimalType = "Bird",
                            Breed = "Parrot",
                            CallName = "Sylvester",
                            Color = "Blue/Green/Red",
                            CustomerId = 6,
                            Name = "Free falling",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 14,
                            AnimalType = "Hamster",
                            Breed = "Hamster",
                            CallName = "squeaky",
                            Color = "Brown",
                            CustomerId = 7,
                            Name = "Little ham",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 15,
                            AnimalType = "Elephant",
                            Breed = "Elephant",
                            CallName = "Biggie",
                            Color = "Grey",
                            CustomerId = 8,
                            Name = "The big one",
                            Weight = 5000.0
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Practices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            City = "Brugge",
                            CloseTime = new DateTime(2021, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "deberenakker@proximus.be",
                            Name = "De Berenakker",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0478 12 34 56",
                            Postal = "8000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Beernemstraat 1",
                            City = "Beernem",
                            CloseTime = new DateTime(2021, 1, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dedierenvriend@proximus.be",
                            Name = "De Dierenvriend",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050 12 12 12",
                            Postal = "8730"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 21",
                            City = "Oedelem",
                            CloseTime = new DateTime(2021, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hetplatteland@proximus.be",
                            Name = "Het platteland",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050 01 02 03",
                            Postal = "8730"
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General Veterinarian",
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Description = "diagnosis and management of complex diseases related to one or more internal organ systems",
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 3,
                            Description = "repair and treatment of conditions through physical interventions, often by cutting into the body. A Specialist Surgeon is trained in assessing whether a surgery is truly in the best interest of the patient.",
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "treatment of patients who are at death’s door, with life threatening conditions (including emergencies)",
                            Name = "Critical Care"
                        },
                        new
                        {
                            Id = 5,
                            Description = "management and treatment of cancer using chemotherapy, radiation, and/or surgery",
                            Name = "Medical, radiation"
                        },
                        new
                        {
                            Id = 6,
                            Description = "treatment of skin, fur, and ear conditions",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 7,
                            Description = "treatment and surgery of eye conditions",
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 8,
                            Description = "treatment of muscular or skeletal conditions without surgery. This can include sports performance, the management of injury and age related issues, or recovery from surgery.",
                            Name = "Sports medicine & rehabilitation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "treatment and surgery of diseases to do with the brain, spinal cord, and muscles (all part of the nervous system)",
                            Name = "Neurology & neurosurgery"
                        },
                        new
                        {
                            Id = 10,
                            Description = "veterinary specialists dealing with species that are not dogs or cats (eg. birds, reptiles, rabbits, etc). These specialties can be broken down into more specific species such as Avian Specialist",
                            Name = "Avian & Exotics"
                        },
                        new
                        {
                            Id = 11,
                            Description = "acquiring and interpreting medical images (e.g. X-ray, CT, ultrasound, and MRI) to assist with diagnosis and treatment",
                            Name = "Diagnostic imaging"
                        },
                        new
                        {
                            Id = 12,
                            Description = " experts in pain relief and management (particularly during surgery), focusing on patient comfort and welfare. Anaesthetists help provide the safest sedation and anaesthetic options for each individual based on their medical condition",
                            Name = "Anaesthesia"
                        },
                        new
                        {
                            Id = 13,
                            Description = "determining the cause and nature of diseases by examining and testing body tissues, cells, and fluids",
                            Name = "Pathology"
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            Birth = new DateTime(1991, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "vl@deberenakker.be",
                            FirstName = "Veerle",
                            LastName = "Lauwers",
                            Phone = "0478 12 34 56",
                            Postal = "8000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Langestraat 56",
                            Birth = new DateTime(1981, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "wb@gmail.com",
                            FirstName = "Wim",
                            LastName = "Budddaert",
                            Phone = "0478 12 69 99",
                            Postal = "9000"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 13",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Oedelem",
                            Email = "kdv@gmail.com",
                            FirstName = "Ken",
                            LastName = "De Vos",
                            Phone = "0488 11 43 39",
                            Postal = "8730"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lippenslaan 12",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "SanneDZ@telenet.be",
                            FirstName = "Sanne",
                            LastName = "De Zon",
                            Phone = "0032459698738",
                            Postal = "8310"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kerkstraat 23",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "Lottevanputte@proximus.be",
                            FirstName = "Lotte",
                            LastName = "Vanputte",
                            Phone = "0032459623438",
                            Postal = "8000"
                        });
                });

            modelBuilder.Entity("SpecialtyVeterinarian", b =>
                {
                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariansId")
                        .HasColumnType("int");

                    b.HasKey("SpecialtiesId", "VeterinariansId");

                    b.HasIndex("VeterinariansId");

                    b.ToTable("SpecialtyVeterinarian");

                    b.HasData(
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 1
                        },
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 2
                        },
                        new
                        {
                            SpecialtiesId = 2,
                            VeterinariansId = 3
                        },
                        new
                        {
                            SpecialtiesId = 2,
                            VeterinariansId = 4
                        },
                        new
                        {
                            SpecialtiesId = 3,
                            VeterinariansId = 5
                        },
                        new
                        {
                            SpecialtiesId = 3,
                            VeterinariansId = 1
                        },
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 3
                        });
                });

            modelBuilder.Entity("MedicationPet", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracticeVeterinarian", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Practice", null)
                        .WithMany()
                        .HasForeignKey("PracticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", null)
                        .WithMany()
                        .HasForeignKey("VeterinariansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Customer", "Customer")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Pri.Pawpi.Core.Entities.ApplicationUser", "CustomerId");

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", "Veterinarian")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Pri.Pawpi.Core.Entities.ApplicationUser", "VeterinarianId");

                    b.Navigation("Customer");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Consultation", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Pet", "Pet")
                        .WithMany("Consultations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", "Veterinarian")
                        .WithMany("Consultations")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Practice", "Practice")
                        .WithMany("Customers")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SpecialtyVeterinarian", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", null)
                        .WithMany()
                        .HasForeignKey("VeterinariansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Practice", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Veterinarian", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
