// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.Pawpi.Infrastructure.Data;

#nullable disable

namespace Pri.Pawpi.Infrastructure.Migrations
{
    [DbContext(typeof(PawpiDbContext))]
    [Migration("20231112134351_UpdateUserSeeder")]
    partial class UpdateUserSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MedicationPet", b =>
                {
                    b.Property<int>("MedicationsId")
                        .HasColumnType("int");

                    b.Property<int>("PetsId")
                        .HasColumnType("int");

                    b.HasKey("MedicationsId", "PetsId");

                    b.HasIndex("PetsId");

                    b.ToTable("MedicationPet");

                    b.HasData(
                        new
                        {
                            MedicationsId = 1,
                            PetsId = 1
                        },
                        new
                        {
                            MedicationsId = 2,
                            PetsId = 1
                        },
                        new
                        {
                            MedicationsId = 3,
                            PetsId = 2
                        },
                        new
                        {
                            MedicationsId = 4,
                            PetsId = 2
                        },
                        new
                        {
                            MedicationsId = 5,
                            PetsId = 3
                        },
                        new
                        {
                            MedicationsId = 6,
                            PetsId = 3
                        },
                        new
                        {
                            MedicationsId = 7,
                            PetsId = 4
                        },
                        new
                        {
                            MedicationsId = 8,
                            PetsId = 4
                        },
                        new
                        {
                            MedicationsId = 9,
                            PetsId = 5
                        },
                        new
                        {
                            MedicationsId = 10,
                            PetsId = 5
                        },
                        new
                        {
                            MedicationsId = 11,
                            PetsId = 6
                        },
                        new
                        {
                            MedicationsId = 12,
                            PetsId = 6
                        },
                        new
                        {
                            MedicationsId = 13,
                            PetsId = 7
                        },
                        new
                        {
                            MedicationsId = 14,
                            PetsId = 7
                        },
                        new
                        {
                            MedicationsId = 15,
                            PetsId = 8
                        },
                        new
                        {
                            MedicationsId = 13,
                            PetsId = 8
                        },
                        new
                        {
                            MedicationsId = 14,
                            PetsId = 9
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "310c6210-e78e-4298-9bc2-2eeda8eecc7f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "1213db75-aaeb-46e4-bb6b-1c05f149cfd8",
                            Name = "Veterinarian",
                            NormalizedName = "VETERINARIAN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "ce186cc5-6768-4bad-9afb-9222d28645a5",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "13",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "14",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "15",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "16",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "17",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PracticeVeterinarian", b =>
                {
                    b.Property<int>("PracticesId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariansId")
                        .HasColumnType("int");

                    b.HasKey("PracticesId", "VeterinariansId");

                    b.HasIndex("VeterinariansId");

                    b.ToTable("PracticeVeterinarian");

                    b.HasData(
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 1
                        },
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 2
                        },
                        new
                        {
                            PracticesId = 2,
                            VeterinariansId = 3
                        },
                        new
                        {
                            PracticesId = 2,
                            VeterinariansId = 4
                        },
                        new
                        {
                            PracticesId = 3,
                            VeterinariansId = 5
                        },
                        new
                        {
                            PracticesId = 3,
                            VeterinariansId = 1
                        },
                        new
                        {
                            PracticesId = 1,
                            VeterinariansId = 3
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("VeterinarianId")
                        .IsUnique()
                        .HasFilter("[VeterinarianId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18aa3b73-6361-453f-8be0-eb3ee7b4f52f",
                            CustomerId = 1,
                            Email = "svends@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SVENDS@GMAIL.COM",
                            NormalizedUserName = "SVENDS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMkrY0pjoVrM9gRRPDkXLD9PVmfVS+yS7uYnAMYaub2ehSKvYC+2nDlnuwxeX7kf1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8196ab42-9be0-4ce4-ae6f-d5ab8be02326",
                            TwoFactorEnabled = false,
                            UserName = "svends@gmail.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1fc5cbc6-94e9-4649-baf4-4a31cecc8319",
                            CustomerId = 2,
                            Email = "vb@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VB@GMAIL.COM",
                            NormalizedUserName = "VB@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHMljicxTOywpYYw8fGxL1hYy6UY8UtvNSfIYnS5uMWRN4hm3b8xN3S+lS3lFZ7D7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2a2c691-dbf3-477b-9933-c9f75ec4a000",
                            TwoFactorEnabled = false,
                            UserName = "vb@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2597a56c-7354-476c-83dd-972d40287989",
                            CustomerId = 3,
                            Email = "kdv@outlook.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KDV@OUTLOOK.COM",
                            NormalizedUserName = "KDV@OUTLOOK.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKZOtxXlajIvKtabBso9UOcx6s2+X+XDPyI265O16JIy402i/p1CulJpJbT5319smA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35055645-53cb-4b49-b494-9c8dc5b34de4",
                            TwoFactorEnabled = false,
                            UserName = "kdv@outlook.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "94448a47-7731-4c09-bb20-82332903ca56",
                            CustomerId = 4,
                            Email = "makkermaat@telenet.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MAKKERMAAT@TELENET.BE",
                            NormalizedUserName = "MAKKERMAAT@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEMApDlb/9zOmRx4k8aNrl56rpzciGU1DS0bR+g1ssLqm9DViFoA0/M9Efx7WPGBFqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2f9eac45-c2c9-4e5a-82b4-5ecd4c6bf59b",
                            TwoFactorEnabled = false,
                            UserName = "makkermaat@telenet.be"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1c6f025-1407-43e1-8617-ac66bd00646a",
                            CustomerId = 5,
                            Email = "sarahdv@proximus.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAHDV@PROXIMUS.BE",
                            NormalizedUserName = "SARAHDV@PROXIMUS.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAED4Jv1s2e7wJNj0Q9hSpjW9Ai53uMdO5tIqJumpaOJ9LUbTdj2pk6MahsCdBgHlEzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98ce17a0-91d6-4571-a9de-726759484b09",
                            TwoFactorEnabled = false,
                            UserName = "sarahdv@proximus.be"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5799fcf9-73d4-4984-91d4-55d334c8723e",
                            CustomerId = 6,
                            Email = "jdv@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JDV@YAHOO.COM",
                            NormalizedUserName = "JDV@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGekDwAYjcG18xpq931vxStwBx/XIer8qp6j7BauW410vQBx10mjiVEUSjfUcY6OIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "249e798b-ee33-4621-a027-90c5a3a5c562",
                            TwoFactorEnabled = false,
                            UserName = "jdv@yahoo.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b32212d1-596d-4b01-9c74-dee975551168",
                            CustomerId = 7,
                            Email = "mieketjeeeeh@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MIEKETJEEEEH@GMAIL.COM",
                            NormalizedUserName = "MIEKETJEEEEH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEH699RGIaSIYNnLCviExxSD8XBrHsQ7Yku5GqLtBtAaISQtIIpSbbJLMjV8B9KHk8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "182960d0-0f81-4f6b-b410-d36f3530739e",
                            TwoFactorEnabled = false,
                            UserName = "mieketjeeeeh@gmail.com"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "866ee216-b523-4c11-90fd-de81d6fe6e08",
                            CustomerId = 8,
                            Email = "jeffkeeuh@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JEFFKEEUH@GMAIL.COM",
                            NormalizedUserName = "JEFFKEEUH@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBErgoWvxIXQQfeNbknHJpDSLLhyvz+3tMF2AUOH9K+ZbLMR7RLUd+uskkd3X1iuyg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6485c20-67ef-452e-80ff-ed71d0fac10b",
                            TwoFactorEnabled = false,
                            UserName = "jeffkeeuh@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5e764158-65ef-4fc2-a979-4ce2c9af3e50",
                            CustomerId = 9,
                            Email = "hansdissen@telenet.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HANSDISSEN@TELENET.BE",
                            NormalizedUserName = "HANSDISSEN@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEBCgahMmir5IZoNu0yELKxOxOVzlbutwLzqGPUeVVuy0bZnYjeAwZfeKquBf3SySag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee715df3-3184-4a90-8887-3ab75b786c9d",
                            TwoFactorEnabled = false,
                            UserName = "hansdissen@telenet.be"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "675e105d-868c-40d9-aca7-9ce66160e435",
                            CustomerId = 10,
                            Email = "chaydz@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHAYDZ@GMAIL.COM",
                            NormalizedUserName = "CHAYDZ@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEC0SODlSodwGFwU69TMwsS+mdaunZsH7GuEmg+t2iqujmf5oyWUyGsKa5iyOn5l7nQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "965d97e4-df37-4722-ac97-159a1e991b01",
                            TwoFactorEnabled = false,
                            UserName = "chaydz@gmail.com"
                        },
                        new
                        {
                            Id = "12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f58a6116-f685-469a-b10d-b0c2ba21949b",
                            CustomerId = 999,
                            Email = "Customer@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@TEST.COM",
                            NormalizedUserName = "CUSTOMER@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEM4Rt/W2KwiVhat/VdKWtqoywqs17VIMwI3Fn29Wbdj+dJZiVv6Tb2yl1zE2pb0WHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e1aac0b-783a-47e1-ab43-0de78e58ffb8",
                            TwoFactorEnabled = false,
                            UserName = "Customer@test.com"
                        },
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Email = "admin@pawpi.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PAWPI.COM",
                            NormalizedUserName = "ADMIN@PAWPI.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEM68iFeSOCZgtA24ecbGFpZQUnRnGc78+MiqY8+Yidv1ybAgmGd8H1J4R9nCrYvouw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "admin@pawpi.com"
                        },
                        new
                        {
                            Id = "13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69a6e5f9-c7bb-452a-90f7-07a9f888297e",
                            Email = "vl@deberenakker.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VL@DEBERENAKKER.BE",
                            NormalizedUserName = "VL@DEBERENAKKER.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEI53oAaBGkEqwJxNF4DSzkEL1iqinyyaJNTAmgbcsHSL2VY2DmBHXfBG9v+iHTRVIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a223c01f-edac-43e5-a5a4-9fa4cdbac106",
                            TwoFactorEnabled = false,
                            UserName = "vl@deberenakker.be",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = "14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b5c136c-a9bb-4165-96f4-2638ac910dcc",
                            Email = "wb@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WB@GMAIL.COM",
                            NormalizedUserName = "WB@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDeHmpIrfH2vHIgSc3DNyC9LslepDW/O0/4aJso2l02SaYQOPBZbmAJZuJmB+QCC+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a95f2dd-eecd-4a22-89c1-b64ec7294d84",
                            TwoFactorEnabled = false,
                            UserName = "wb@gmail.com",
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = "15",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cb55483-47cb-486d-bdf2-0e63681d77c7",
                            Email = "kdv@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KDV@GMAIL.COM",
                            NormalizedUserName = "KDV@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGVVoSmropNcq8Vd9eU8cugnxU7WFY5XnpXiZKtFfOJbwjmIChKbeIZ2gTqjC7UPfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d322f2b2-3a46-4dee-b980-97c005fc4b85",
                            TwoFactorEnabled = false,
                            UserName = "kdv@gmail.com",
                            VeterinarianId = 3
                        },
                        new
                        {
                            Id = "16",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ceea30b1-1d46-4f29-87f6-c534f7711bf7",
                            Email = "SanneDZ@telenet.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SANNEDZ@TELENET.BE",
                            NormalizedUserName = "SANNEDZ@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEPISjFOojyBIsFh28/M3UUBlAmSSdFmz6ZYZjGKVihbv7XER3U6B5hcLkdYn3xSmqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c0e5649-9989-4631-9beb-9f123b730efb",
                            TwoFactorEnabled = false,
                            UserName = "SanneDZ@telenet.be",
                            VeterinarianId = 4
                        },
                        new
                        {
                            Id = "17",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11c94a9e-7cd7-4a73-ad2c-46c176a8119c",
                            Email = "Lottevanputte@proximus.be",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LOTTEVANPUTTE@PROXIMUS.BE",
                            NormalizedUserName = "LOTTEVANPUTTE@PROXIMUS.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEEwBBAE0lqJQfyuSe5m0tEVXERvQ+BPEhjN6dda8aJQHBjOYJHxbLPaTK29T6sVwVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "816e1945-8389-40fe-a49b-3247a068e1a2",
                            TwoFactorEnabled = false,
                            UserName = "Lottevanputte@proximus.be",
                            VeterinarianId = 5
                        },
                        new
                        {
                            Id = "18",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8804bbba-041f-4cab-8473-27f89c946178",
                            Email = "Veterinarian@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VETERINARIAN@TEST.COM",
                            NormalizedUserName = "VETERINARIAN@TEST.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELj2t/eZHk8TBYwkttYN4vJmNb7AZnJdY7Tz5Q4fV5NP6iQrYwa32oZOSOiaqb+bnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "71cddbd5-3210-4d0e-b7d5-da392caab5c0",
                            TwoFactorEnabled = false,
                            UserName = "Veterinarian@test.com",
                            VeterinarianId = 999
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfConsultation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocumentFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Treatment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfConsultation = new DateTime(2023, 11, 12, 14, 43, 50, 763, DateTimeKind.Local).AddTicks(2910),
                            Diagnosis = "Controle",
                            Notes = "Staat wat mager",
                            PetId = 1,
                            Title = "First Consultation",
                            Treatment = "None",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfConsultation = new DateTime(2023, 11, 12, 14, 43, 50, 763, DateTimeKind.Local).AddTicks(2943),
                            Diagnosis = "Hond in kwestie heeft gras gegeten en moet overgeven",
                            Notes = "",
                            PetId = 1,
                            Title = "Overgeven",
                            Treatment = "Gaat over",
                            VeterinarianId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfConsultation = new DateTime(2023, 11, 12, 14, 43, 50, 763, DateTimeKind.Local).AddTicks(2946),
                            Diagnosis = "Vaccinatie",
                            Notes = "",
                            PetId = 2,
                            Title = "Vaccinatie",
                            Treatment = "",
                            VeterinarianId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfConsultation = new DateTime(2023, 11, 12, 14, 43, 50, 763, DateTimeKind.Local).AddTicks(2949),
                            Diagnosis = "Tanden zijn slecht onderhouden",
                            Notes = "",
                            PetId = 3,
                            Title = "Tanden",
                            Treatment = "Medicatie en poeten",
                            VeterinarianId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateOfConsultation = new DateTime(2023, 11, 12, 14, 43, 50, 763, DateTimeKind.Local).AddTicks(2951),
                            Diagnosis = "Vaccinatie",
                            Notes = "",
                            PetId = 2,
                            Title = "Vaccinatie",
                            Treatment = "",
                            VeterinarianId = 3
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PracticeId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            Birth = new DateTime(1991, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "svends@gmail.com",
                            FirstName = "Sven",
                            LastName = "De Schagt",
                            Phone = "0478 12 34 56",
                            Postal = "8000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Langestraat 56",
                            Birth = new DateTime(1981, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "vb@gmail.com",
                            FirstName = "Jan",
                            LastName = "Vanbergen",
                            Phone = "0478 12 69 99",
                            Postal = "9000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 134",
                            Birth = new DateTime(1971, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Oedelem",
                            Email = "kdv@outlook.com",
                            FirstName = "Karel",
                            LastName = "De Vos",
                            Phone = "0488 11 43 39",
                            Postal = "8730",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lippenslaan 45",
                            Birth = new DateTime(1966, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "makkermaat@telenet.be",
                            FirstName = "Makker",
                            LastName = "Maat",
                            Phone = "0032459698738",
                            Postal = "8310",
                            PracticeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "lachenstraat 21",
                            Birth = new DateTime(2010, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "sarahdv@proximus.be",
                            FirstName = "Sarah",
                            LastName = "De Vriendt",
                            Phone = "0032459698738",
                            Postal = "8000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "zieligestraat 101",
                            Birth = new DateTime(1970, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "jdv@yahoo.com",
                            FirstName = "Johan",
                            LastName = "De Vriendt",
                            Phone = "2345563223",
                            Postal = "8310",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "stommestrat 102",
                            Birth = new DateTime(1940, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "mieketjeeeeh@gmail.com",
                            FirstName = "Mieke",
                            LastName = "Vanoverpoel",
                            Phone = "0032567844",
                            Postal = "9000",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "stommestrat 102",
                            Birth = new DateTime(1950, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "jeffkeeuh@gmail.com",
                            FirstName = "Jef",
                            LastName = "Vanoverpoel",
                            Phone = "2234565463",
                            Postal = "9000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "lachenstraat 21",
                            Birth = new DateTime(2010, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "hansdissen@telenet.be",
                            FirstName = "Hans",
                            LastName = "Dissen",
                            Phone = "0032459698738",
                            Postal = "8000",
                            PracticeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "Hulstlo 21",
                            Birth = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Beernem",
                            Email = "chaydz@gmail.com",
                            FirstName = "Chayenne",
                            LastName = "De Zutter",
                            Phone = "0032459698738",
                            Postal = "8730",
                            PracticeId = 1
                        },
                        new
                        {
                            Id = 999,
                            Address = "Test",
                            Birth = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Test",
                            Email = "Customer@test.com",
                            FirstName = "Test",
                            LastName = "Test",
                            Phone = "0032459698738",
                            Postal = "9999",
                            PracticeId = 1
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SideEffects")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dosage = "2",
                            Frequency = "Once a day",
                            Name = "Rimadyl",
                            Notes = "Rimadyl is a non-steroidal anti-inflammatory drug (NSAID) of the propionic acid class that is used in humans and animals for the relief of pain and inflammation associated with osteoarthritis and for the control of postoperative pain associated with soft tissue and orthopedic surgeries in dogs."
                        },
                        new
                        {
                            Id = 2,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Tramadol",
                            Notes = "Tramadol, sold under the brand name Ultram among others, is an opioid pain medication used to treat moderate to moderately severe pain. When taken by mouth in an immediate-release formulation, the onset of pain relief usually begins within an hour."
                        },
                        new
                        {
                            Id = 3,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Gabapentin",
                            Notes = "Gabapentin, sold under the brand name Neurontin among others, is an anticonvulsant medication used to treat partial seizures, neuropathic pain, hot flashes, and restless legs syndrome."
                        },
                        new
                        {
                            Id = 4,
                            Dosage = "1",
                            Frequency = "Three times a day",
                            Name = "Apoquel",
                            Notes = "Apoquel is a medication that is used to treat itching and inflammation in dogs caused by a variety of diagnoses. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls itching within 24 hours."
                        },
                        new
                        {
                            Id = 5,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Cerenia",
                            Notes = "Cerenia is a medication that is used to treat vomiting in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls vomiting within 24 hours."
                        },
                        new
                        {
                            Id = 6,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Clavamox",
                            Notes = "Clavamox is a medication that is used to treat bacterial infections in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls bacterial infections within 24 hours."
                        },
                        new
                        {
                            Id = 7,
                            Dosage = "1",
                            Frequency = "Tree times a day",
                            Name = "Doxycycline",
                            Notes = "Doxycycline is a medication that is used to treat bacterial infections in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls bacterial infections within 24 hours."
                        },
                        new
                        {
                            Id = 8,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Enalapril",
                            Notes = "Enalapril is a medication that is used to treat heart failure in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls heart failure within 24 hours."
                        },
                        new
                        {
                            Id = 9,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Famotidine",
                            Notes = "Famotidine is a medication that is used to treat stomach ulcers in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls stomach ulcers within 24 hours."
                        },
                        new
                        {
                            Id = 10,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Fluoxetine",
                            Notes = "Fluoxetine is a medication that is used to treat anxiety in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls anxiety within 24 hours."
                        },
                        new
                        {
                            Id = 11,
                            Dosage = "1",
                            Frequency = "Twice a day",
                            Name = "Metronidazole",
                            Notes = "Metronidazole is a medication that is used to treat diarrhea in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls diarrhea within 24 hours."
                        },
                        new
                        {
                            Id = 12,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Mirtazapine",
                            Notes = "Mirtazapine is a medication that is used to treat appetite loss in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls appetite loss within 24 hours."
                        },
                        new
                        {
                            Id = 13,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Prednisone",
                            Notes = "Prednisone is a medication that is used to treat inflammation in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls inflammation within 24 hours."
                        },
                        new
                        {
                            Id = 14,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Praziquantel",
                            Notes = "Praziquantel is a medication that is used to treat tapeworms in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls tapeworms within 24 hours."
                        },
                        new
                        {
                            Id = 15,
                            Dosage = "1",
                            Frequency = "Once a day",
                            Name = "Simparica",
                            Notes = "Simparica is a medication that is used to treat fleas and ticks in dogs. It is a fast-acting drug that starts to work within 4 hours of administration and effectively controls fleas and ticks within 24 hours."
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CallName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PedigreeFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Dog",
                            Breed = "Golden Retriever",
                            CallName = "Bella",
                            Color = "Golden",
                            CustomerId = 1,
                            Name = "Dunehills Love at first sight",
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Dog",
                            Breed = "Australian Shepherd",
                            CallName = "Luna",
                            Color = "White/Brown",
                            CustomerId = 1,
                            Name = "New glory to the moon",
                            Weight = 20.0
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Dog",
                            Breed = "New Foundland",
                            CallName = "Sky",
                            Color = "Black",
                            CustomerId = 2,
                            Name = "West horizon blue sky",
                            Weight = 50.0
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = "Dog",
                            Breed = "Chihuahua",
                            CallName = "Ratty",
                            Color = "Brown",
                            CustomerId = 3,
                            Name = "Left angle handbag",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 5,
                            AnimalType = "Dog",
                            Breed = "German Shepherd",
                            CallName = "Doug",
                            Color = "Black",
                            CustomerId = 2,
                            Name = "Dark sky thunderstorm",
                            Weight = 40.0
                        },
                        new
                        {
                            Id = 6,
                            AnimalType = "Cat",
                            Breed = "Persian",
                            CallName = "Sunny",
                            Color = "White",
                            CustomerId = 4,
                            Name = "Seven lives to the sun",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 7,
                            AnimalType = "Cat",
                            Breed = "Ragdoll",
                            CallName = "Ellie",
                            Color = "Brown",
                            CustomerId = 5,
                            Name = "The last of us",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 8,
                            AnimalType = "Cat",
                            Breed = "Maine Coon",
                            CallName = "Mio",
                            Color = "White",
                            CustomerId = 5,
                            Name = "Chronicles of ouroboros",
                            Weight = 10.0
                        },
                        new
                        {
                            Id = 9,
                            AnimalType = "Fish",
                            Breed = "Goldfish",
                            CallName = "blub",
                            Color = "Gold",
                            CustomerId = 1,
                            Name = "Sharktale the blue",
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 10,
                            AnimalType = "Fish",
                            Breed = "Droge vis",
                            CallName = "sink",
                            Color = "Blue",
                            CustomerId = 2,
                            Name = "Dark cold blue sea",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 11,
                            AnimalType = "Horse",
                            Breed = "Horse",
                            CallName = "Stallion",
                            Color = "Brown",
                            CustomerId = 3,
                            Name = "Big horse on the field",
                            Weight = 500.0
                        },
                        new
                        {
                            Id = 12,
                            AnimalType = "Snake",
                            Breed = "Viper",
                            CallName = "Noodle",
                            Color = "Green",
                            CustomerId = 6,
                            Name = "Slithering down the road",
                            Weight = 1.0
                        },
                        new
                        {
                            Id = 13,
                            AnimalType = "Bird",
                            Breed = "Parrot",
                            CallName = "Sylvester",
                            Color = "Blue/Green/Red",
                            CustomerId = 6,
                            Name = "Free falling",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 14,
                            AnimalType = "Hamster",
                            Breed = "Hamster",
                            CallName = "squeaky",
                            Color = "Brown",
                            CustomerId = 7,
                            Name = "Little ham",
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 15,
                            AnimalType = "Elephant",
                            Breed = "Elephant",
                            CallName = "Biggie",
                            Color = "Grey",
                            CustomerId = 8,
                            Name = "The big one",
                            Weight = 5000.0
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Practices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            City = "Brugge",
                            CloseTime = new DateTime(2021, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "deberenakker@proximus.be",
                            Name = "De Berenakker",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0478 12 34 56",
                            Postal = "8000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Beernemstraat 1",
                            City = "Beernem",
                            CloseTime = new DateTime(2021, 1, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dedierenvriend@proximus.be",
                            Name = "De Dierenvriend",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050 12 12 12",
                            Postal = "8730"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 21",
                            City = "Oedelem",
                            CloseTime = new DateTime(2021, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hetplatteland@proximus.be",
                            Name = "Het platteland",
                            OpenTime = new DateTime(2021, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050 01 02 03",
                            Postal = "8730"
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General Veterinarian",
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Description = "diagnosis and management of complex diseases related to one or more internal organ systems",
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 3,
                            Description = "repair and treatment of conditions through physical interventions, often by cutting into the body. A Specialist Surgeon is trained in assessing whether a surgery is truly in the best interest of the patient.",
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "treatment of patients who are at death’s door, with life threatening conditions (including emergencies)",
                            Name = "Critical Care"
                        },
                        new
                        {
                            Id = 5,
                            Description = "management and treatment of cancer using chemotherapy, radiation, and/or surgery",
                            Name = "Medical, radiation"
                        },
                        new
                        {
                            Id = 6,
                            Description = "treatment of skin, fur, and ear conditions",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 7,
                            Description = "treatment and surgery of eye conditions",
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 8,
                            Description = "treatment of muscular or skeletal conditions without surgery. This can include sports performance, the management of injury and age related issues, or recovery from surgery.",
                            Name = "Sports medicine & rehabilitation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "treatment and surgery of diseases to do with the brain, spinal cord, and muscles (all part of the nervous system)",
                            Name = "Neurology & neurosurgery"
                        },
                        new
                        {
                            Id = 10,
                            Description = "veterinary specialists dealing with species that are not dogs or cats (eg. birds, reptiles, rabbits, etc). These specialties can be broken down into more specific species such as Avian Specialist",
                            Name = "Avian & Exotics"
                        },
                        new
                        {
                            Id = 11,
                            Description = "acquiring and interpreting medical images (e.g. X-ray, CT, ultrasound, and MRI) to assist with diagnosis and treatment",
                            Name = "Diagnostic imaging"
                        },
                        new
                        {
                            Id = 12,
                            Description = " experts in pain relief and management (particularly during surgery), focusing on patient comfort and welfare. Anaesthetists help provide the safest sedation and anaesthetic options for each individual based on their medical condition",
                            Name = "Anaesthesia"
                        },
                        new
                        {
                            Id = 13,
                            Description = "determining the cause and nature of diseases by examining and testing body tissues, cells, and fluids",
                            Name = "Pathology"
                        });
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kerkstraat 1",
                            Birth = new DateTime(1991, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "vl@deberenakker.be",
                            FirstName = "Veerle",
                            LastName = "Lauwers",
                            Phone = "0478 12 34 56",
                            Postal = "8000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Langestraat 56",
                            Birth = new DateTime(1981, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Gent",
                            Email = "wb@gmail.com",
                            FirstName = "Wim",
                            LastName = "Budddaert",
                            Phone = "0478 12 69 99",
                            Postal = "9000"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Knesselarestraat 13",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Oedelem",
                            Email = "kdv@gmail.com",
                            FirstName = "Ken",
                            LastName = "De Vos",
                            Phone = "0488 11 43 39",
                            Postal = "8730"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lippenslaan 12",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Knokke",
                            Email = "SanneDZ@telenet.be",
                            FirstName = "Sanne",
                            LastName = "De Zon",
                            Phone = "0032459698738",
                            Postal = "8310"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kerkstraat 23",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brugge",
                            Email = "Lottevanputte@proximus.be",
                            FirstName = "Lotte",
                            LastName = "Vanputte",
                            Phone = "0032459623438",
                            Postal = "8000"
                        },
                        new
                        {
                            Id = 999,
                            Address = "Test",
                            Birth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Test",
                            Email = "Veterinarian@test.com",
                            FirstName = "Test",
                            LastName = "Test",
                            Phone = "0032459698738",
                            Postal = "9999"
                        });
                });

            modelBuilder.Entity("SpecialtyVeterinarian", b =>
                {
                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinariansId")
                        .HasColumnType("int");

                    b.HasKey("SpecialtiesId", "VeterinariansId");

                    b.HasIndex("VeterinariansId");

                    b.ToTable("SpecialtyVeterinarian");

                    b.HasData(
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 1
                        },
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 2
                        },
                        new
                        {
                            SpecialtiesId = 2,
                            VeterinariansId = 3
                        },
                        new
                        {
                            SpecialtiesId = 2,
                            VeterinariansId = 4
                        },
                        new
                        {
                            SpecialtiesId = 3,
                            VeterinariansId = 5
                        },
                        new
                        {
                            SpecialtiesId = 3,
                            VeterinariansId = 1
                        },
                        new
                        {
                            SpecialtiesId = 1,
                            VeterinariansId = 3
                        });
                });

            modelBuilder.Entity("MedicationPet", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PracticeVeterinarian", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Practice", null)
                        .WithMany()
                        .HasForeignKey("PracticesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", null)
                        .WithMany()
                        .HasForeignKey("VeterinariansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Customer", "Customer")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Pri.Pawpi.Core.Entities.ApplicationUser", "CustomerId");

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", "Veterinarian")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Pri.Pawpi.Core.Entities.ApplicationUser", "VeterinarianId");

                    b.Navigation("Customer");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Consultation", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Pet", "Pet")
                        .WithMany("Consultations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", "Veterinarian")
                        .WithMany("Consultations")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Practice", "Practice")
                        .WithMany("Customers")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SpecialtyVeterinarian", b =>
                {
                    b.HasOne("Pri.Pawpi.Core.Entities.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Pawpi.Core.Entities.Veterinarian", null)
                        .WithMany()
                        .HasForeignKey("VeterinariansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Customer", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Pet", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Practice", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Pri.Pawpi.Core.Entities.Veterinarian", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
